In [2]:
import pandas as pd
import numpy as np
from pathlib import Path

In [6]:
# load data
try:
    BASE_DIR = Path(__file__).resolve().parent
except NameError:
    # Jupyter Notebook 环境下没有 __file__ 变量
    BASE_DIR = Path.cwd()

DATASETS_DIR = BASE_DIR / "Datasets"

DATASETS_DIR = BASE_DIR / "Datasets"

working_hours = pd.read_csv(
    DATASETS_DIR / "Horas de Trabalho (Our World in Data)/annual-working-hours-per-worker.csv"
)
happiness = pd.read_csv(
    DATASETS_DIR / "World Happiness Report (Kaggle)/happy.csv",
    sep=";",
    decimal=","
)
gdp_per_capita = pd.read_csv(
    DATASETS_DIR / "PIB per Capita (World Bank Open Data)/API_NY.GDP.PCAP.CD_DS2_en_csv_v2_468810.csv",
    # we have to skip the first 4 lintes because they're are about metadata because pandas was trying to parse them as data
    skiprows=4
)

In [4]:
# we make copies so that we don't "ruin" or compromise the original datasets
working_hours_copy = working_hours.copy()
happiness_copy = happiness.copy()

In [5]:
print(working_hours_copy.shape)
print(working_hours_copy.dtypes)
display(working_hours_copy.head())
print(happiness_copy.shape)
print(happiness_copy.dtypes)
display(happiness_copy.head())

(5063, 5)
Entity                                str
Code                                  str
Year                                int64
Working hours per worker          float64
World region according to OWID        str
dtype: object

    Entity Code  Year  Working hours per worker World region according to OWID
0  Albania  ALB  2005                   2343.90                         Europe
1  Albania  ALB  2006                   2333.12                         Europe
2  Albania  ALB  2007                   2334.51                         Europe
3  Albania  ALB  2008                   2195.57                         Europe
4  Albania  ALB  2009                   2191.19                         Europe

(1969, 1)
Data;Rank;Country name;Ladder score;upperwhisker;lowerwhisker;Explained by: Log GDP per capita;Explained by: Social support;Explained by: Healthy life expectancy;Explained by: Freedom to make life choices;Explained by: Generosity;Explained by: Perceptions of corruption;Dystopia + residual    float64
dtype: object

                                                                                       Data;Rank;Country name;Ladder score;upperwhisker;lowerwhisker;Explained by: Log GDP per capita;Explained by: Social support;Explained by: Healthy life expectancy;Explained by: Freedom to make life choices;Explained by: Generosity;Explained by: Perceptions of corruption;Dystopia + residual
01/01/2024;1;Finland;7       736;7 81;7  662;1 749;1   783;0   824;0 986;0 11;0 502;1                                              782.0
01/01/2023;143;Afghanistan;1 721;1 775;1 667;0 628;0;0 242;0;0 091;0 088;0 672  nan                                                  NaN
01/01/2022;137;Afghanistan;1 859;1 923;1 795;0 645;0;0 087;0;0 093;0 059;0 976  nan                                                  NaN
01/01/2021;146;Afghanistan;2 404;2 469;2 339;0 758;0;0 289;0;0 089;0 005;1 263  nan                                                  NaN
01/01/2020;150;Afghanistan;2 523;2 596;2 449;0 37;0;0  126;0;0 122;0 01;1  895  nan                                                  NaN

In [1]:
# clean gdp_per_capita data

gdp_per_capita_copy = gdp_per_capita.copy()
# display(gdp_per_capita_copy.head())

# Delete unnecessary columns. 
gdp_clean = gdp_per_capita_copy.drop(
    columns=["Indicator Name", "Indicator Code", "Unnamed: 70"], 
    errors='ignore'
    )
# Convert the years from columns to rows.
gdp_clean = gdp_clean.melt(
    id_vars =["Country Name", "Country Code"],
    var_name = "Year",
    value_name = "GDP_per_capita"
)
# convert the year from str to num
gdp_clean["Year"]= pd.to_numeric(gdp_clean["Year"])

# select data after 2005
gdp_clean = gdp_clean[gdp_clean["Year"] >= 2005]

# display(gdp_clean.head())
# display(gdp_clean[gdp_clean["Country Code"] == "ABW"].head())

print(gdp_clean.isna().sum())
print(gdp_clean.shape)

missing_gdp = gdp_clean[gdp_clean["GDP_per_capita"].isna()]

display(missing_gdp.head())

NameError: name 'gdp_per_capita' is not defined